# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 10:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('the_big_one', '0006_auto_20151228_0206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='street_name',
        ),
        migrations.RemoveField(
            model_name='address',
            name='street_number',
        ),
    ]
